### ISSUE TITLE
Cannot find module './lib/base'

### ISSUE THREAD

**Issue by aggieben** [OmniSharp/generator-aspnet#580]
### Short issue description

aspnet generator breakswith "Cannot find module './lib/base' error.
### Expected behavior

Normal yeoman menu is presented in console.
### Actual behavior

Output:

```
λ yo aspnet
module.js:328
    throw err;
    ^

Error: Cannot find module './lib/base'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\generator-aspnet\node_modules\yeoman-generator\index.js:41:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```
### Steps to reproduce the behavior

Install latest yo, generator-aspnet.  Run `> yo aspnet`

---
#### OS version (Win/Mac/*Nix?)

Windows 10.0.10586, x64
#### NodeJS version

```
λ node --version
v5.4.0
```
#### Yeoman version

```
λ yo --version
1.7.0
```
#### Generator version

```
λ npm ls -g generator-aspnet -ls=0 --long

│ C:\Users\Benjamin\AppData\Roaming\npm
│
└── generator-aspnet@0.0.93
    Yeoman generator for ASP.NET 5 apps
    git+https://github.com/omnisharp/generator-aspnet.git
    https://github.com/omnisharp/generator-aspnet#readme
```

**Comment by peterblazejewicz** [comment]
Have you upgraded Node from 4.* to 5.* during the process somehow?

**Comment by aggieben** [comment]
I've been on Node 5.4.0 for a little while now.  I don't think anything changed as a result of updating yo or generator-aspnet.

**Comment by peterblazejewicz** [comment]
I haven't been able to recreate this problem with 5.9.* (current latest stable version):
```
PS C:\Users\peter> npm list -g generator-aspnet
C:\Users\peter\AppData\Roaming\npm
└── generator-aspnet@0.0.93
```

Are you able to run `yo` alone?
BTW which version of node you're using? (`npm --version`)

**Comment by aggieben** [comment]
```Powershell
λ npm --version
3.5.3
```

Yes, `yo` by itself works just fine.  Other generators are functional.  For example:

```powershell
λ yo
? 'Allo Ben! What would you like to do? Csharp

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo csharp


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   | marvellous C# generator! |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What type of project do you want to create? Class library
? What's the name of your ASP.NET application? ClassLibrary
   create ClassLibrary\Class1.cs
   create ClassLibrary\ClassLibrary.csproj
   create ClassLibrary\Properties\AssemblyInfo.cs

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__
 ´   `  |° ´ Y `
```

**Comment by peterblazejewicz** [comment]
The generator fails on original tool code:
https://github.com/yeoman/generator/blob/master/lib/index.js#L42
That's too generic information to be really helpful.

**Comment by aggieben** [comment]
What can I do to help troubleshoot?

**Comment by peterblazejewicz** [comment]
Upgrade to Node 5.6 or later does not hurt:
https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/
That's not exactly a solution though.

**Comment by aggieben** [comment]
I upgraded to node 5.9.1 and still experience the same result.

**Comment by sayedihashimi** [comment]
We are shutting this repo down, it's been replaced with `dotnet new`.
