### ISSUE TITLE
Fresh install of generator-aspnet not working

### ISSUE THREAD

**Issue by krippz** [OmniSharp/generator-aspnet#72]
I get this error
```
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9379
        throw e;
              ^
TypeError: Object #<Object> has no method 'on'
    at run (/usr/local/lib/node_modules/generator-aspnet/node_modules/yeoman-generator/lib/base.js:444:21)
    at composeWith (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/base.js:568:15)
    at yoyo._initGenerator (/usr/local/lib/node_modules/yo/yoyo.js:100:8)
    at null.<anonymous> (/usr/local/lib/node_modules/yo/yoyo.js:407:35)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1965:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1902:14)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_%

**Comment by spboyer** [comment]
@krippz please try `npm install -g yo` to fix re: https://github.com/yeoman/generator/issues/762

**Comment by krippz** [comment]
thanks works like a charm!
