### ISSUE TITLE
packagejson Sub Generators error

### ISSUE THREAD

**Issue by rspaulino** [OmniSharp/generator-aspnet#855]
### Short issue description
When I run yo aspnet:packagejson I'm getting an Unhandled 'error'

### Expected behavior
Create a packagejson file

### Actual behavior
yo aspnet:packagejson
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.getNamespace (/usr/local/lib/node_modules/generator-aspnet/configuration.js:35:43)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-aspnet/script-base-basic.js:12:39)
    at Generator.createItem (/usr/local/lib/node_modules/generator-aspnet/packagejson/index.js:12:79)
    at /usr/local/lib/node_modules/generator-aspnet/node_modules/yeoman-generator/lib/base.js:421:16
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

### Steps to reproduce the behavior
yo aspnet:packagejson
<img width="795" alt="screen shot 2016-12-06 at 7 43 18 am" src="https://cloud.githubusercontent.com/assets/378671/20925871/670f0950-bb87-11e6-9f9a-dbeccd8cb5f6.png">

----
#### OS version (Win/Mac/\*Nix?)
macOS 10.12.1

#### NodeJS version
```
node --version
```
v7.2.0

#### Yeoman version
```
yo --version
```
1.8.5

#### Generator version
NPM 3.*:generator-aspnet@0.2.5
```
npm list -g generator-aspnet
```
NPM 2.*:
```
npm ls generator-aspnet -ls=0 --long
```

**Comment by Spinarooni** [comment]
@rspaulino I think this is related to issues #846 and #849.

**Comment by peterblazejewicz** [comment]
Just bug due to coding error. Under updated Node the error arises. WIP

**Comment by peterblazejewicz** [comment]
Fixed. Thanks @rspaulino 
(the update for NPM would wait a while though)

**Comment by rspaulino** [comment]
@peterblazejewicz Great!. Thanks. Yes, I figure.
