### ISSUE TITLE
Dotnet restore throws EntryPointNotFound exception after creating empty web app with generator

### ISSUE THREAD

**Issue by ebetron** [OmniSharp/generator-aspnet#893]
### Short issue description
EntryPointNotFoundException triggered when running "dotnet restore" command after generation of empty web app using generator

### Expected behavior
Project restored and runnable 

### Actual behavior
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'CCRandomGenerateBytes' in DLL '/usr/lib/system/libcommonCrypto'.
   at Interop.CommonCrypto.CCRandomGenerateBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytesApple(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

### Steps to reproduce the behavior
Create an empty ASPNET web app using YO command

----
#### OS version (Win/Mac/\*Nix?)

Mac OS X 10.9.5

#### Dotnet version
1.0.0-preview2-1-003177

#### NodeJS version

6.9.5

#### Yeoman version

1.8.5

#### Generator version
0.2.6

**Comment by peterblazejewicz** [comment]
Does it happen if you create any other sample project (console/class libary)

**Comment by ebetron** [comment]
@peterblazejewicz I get the same error using "dotnet new" command on a new directory.

**Comment by peterblazejewicz** [comment]
Look here:
[Preview 2 tooling known issues](https://github.com/dotnet/core/blob/master/cli/known-issues.md)

Similar one I lookup:
https://github.com/dotnet/cli/issues/3964

**Comment by ebetron** [comment]
Yeah, I see two version of openssl on my machine. What would be the best way of getting rid of them and installing openssl from homebrew all over again?

**Comment by ebetron** [comment]
So i checked which ssl, it's pointing to latest version

But when I run those commands on the .net core download site I get that they exist.

$ mkdir -p /usr/local/lib
$ ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln: /usr/local/lib//libcrypto.1.0.0.dylib: File exists
$ ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
ln: /usr/local/lib//libssl.1.0.0.dylib: File exists

But I still get the error when running "dotnet new"
$ dotnet new

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'CCRandomGenerateBytes' in DLL '/usr/lib/system/libcommonCrypto'.
   at Interop.CommonCrypto.CCRandomGenerateBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytesApple(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

**Comment by peterblazejewicz** [comment]
Have no idea yet. Please repost current finding on `dotnet/cli`:
https://github.com/dotnet/cli/issues

**Comment by ebetron** [comment]
Sure thing! https://github.com/dotnet/cli/issues/5588

**Comment by ebetron** [comment]
Well, if it's the case that 10.9 is not supported, I would suggest putting that info on the readme somewhere.

**Comment by peterblazejewicz** [comment]
The 10.9 is no longer support system for users/development (Apple supports 3 versions). 
https://support.apple.com/en-gb/HT201222
The dot.net advertises 10.11 version or later:
https://www.microsoft.com/net/core#macos

**Comment by ebetron** [comment]
Allright, closing. Thanks for the help @peterblazejewicz , appreciate it!
